### ISSUE TITLE
partitions.py --list gives "AssertionError: Expected arrow in ls output"

### ISSUE THREAD

**Issue by jesusvzla** [Lekensteyn/lglaf#9]
I'm getting this error when trying to run partitions.py --list `AssertionError: Expected arrow in ls output`
What does this mean? Am i doing something wrong?

**Comment by Lekensteyn** [comment]
This meant that the output had an unexpected format and that the block device cannot be found. Could you provide more details, like what device you have?

It would also help if you could add the following line at line 39 (after `names = []`). Note that you must precede it by exactly four spaces:

        _logger.debug("Output is: %r\n", output)

Then run `partitions.py --list --debug`

**Comment by sethmurphy18** [comment]
This is the output I get. Windows 10 (Python 3.5.2)

```
C:\Users\smurp\Projects\lglaf (master)
λ python partitions.py --list --debug
2016-11-06 03:18:18,920 LGLAF.py: DEBUG: Using serial port: COM4
2016-11-06 03:18:19,086 partitions: DEBUG: Output is: 'Hello, I am LAF. Nice to meet you.\x00'

Traceback (most recent call last):
  File "partitions.py", line 277, in <module>
    main()
  File "partitions.py", line 254, in main
    list_partitions(comm, args.partition)
  File "partitions.py", line 125, in list_partitions
    partitions = get_partitions(comm)
  File "partitions.py", line 42, in get_partitions
    assert arrow == '->', "Expected arrow in ls output"
AssertionError: Expected arrow in ls output
```

**Comment by Lekensteyn** [comment]
Argh, those trickers... The expected output is something like `somename -> mmcblkp0`. Might have something to do with #7.

Just to be sure, do all commands fail like this? E.g. try this command `python lglaf.py --debug -c mount` (see README for more examples)

**Comment by sethmurphy18** [comment]
Most commands do fail. Every once in a while I can get in and run basic commands. The main issue I think is that I am running a newer device that is running Marshmallow, so LAF has been updated to counter vulnerabilities.

```
C:\Users\Seth\Projects\lglaf
λ python lglaf.py --debug -c mount
LGLAF.py: DEBUG: Using serial port: COM4
Traceback (most recent call last):
  File "lglaf.py", line 404, in <module>
    main()
  File "lglaf.py", line 386, in main
    try_hello(comm)
  File "lglaf.py", line 290, in try_hello
    data = comm.read(0x20, timeout=HELLO_READ_TIMEOUT)
  File "lglaf.py", line 148, in read
    buff = self._read(need, timeout=timeout)
  File "lglaf.py", line 189, in _read
    return self.f.read(n)
IOError: [Errno 0] Error
```

**Comment by sethmurphy18** [comment]
However, if I skip the hello using `--skip-hello`, I get this message:

```LGLAF.py: WARNING: Expected trailer '|\xff\xff\xfe', found 'k\n\x00r'```

**Comment by sethmurphy18** [comment]
So, I am going to try some sniffing with Wireshark and see what I come up with.

**Comment by steadfasterX** [comment]
This issue happens e.g. on some not all Android versions of the G4. 
The reason is (as mentioned already for the G3 by @tsnoam ) selinux. 
When I can't `ls - /dev/block/bootdevice ` the partitions.py and extract-partions.py will fail (not a surprise..).

I think of 2 solutions on this:

1. `ls -l /dev/block/platform/soc.0/f9824900.sdhci` - I haven't tested that on those problematic Android versions yet though so maybe thats denied as well
(problem: at least f9824900.sdhci is device/model specific!)
2. using the block names of `/proc/partitions` instead or as a fallback:

```
# cat /proc/partitions
major minor  #blocks  name

 179        0   30535680 mmcblk0
 179        1      88064 mmcblk0p1
 179        2        512 mmcblk0p2
 179        3       1024 mmcblk0p3
 179        4       1024 mmcblk0p4
 179        5        512 mmcblk0p5
 179        6        512 mmcblk0p6
 179        7        512 mmcblk0p7
 [....]

```

**Comment by gmt** [comment]
Not anymore on the G5.  Nor will it let you open a file handle to /proc/partitions.  But, I suspect, universally, one can get a list from /dev/block/platform/soc/*/by-name (or something like that, most folks probably know what I mean even if I mixed up the particulars), prune the partitions so as to leave just the raw gpt containers (i.e., on my G5, /dev/block/sd{a,b,c,d,e,f}), open a file handle to each, and then rely on prior art from i.e., util-linux, to do the job of calculating where the physical partitions are to be found based on the available information.

Indeed, so far, that is the only way I can think of, to make this work in a straightforward procedural way; every other means by which lglaf might attempt to glean this information has been made unavailable (perhaps this implication of banning "cat" was an incidental, rather than a deliberate omission, as "fdisk -l" is the obvious next thing to try, once you have access to a block device with a gpt and little more.  It's a bit disappointing that there seems to be no way to get the available tools (mainly just ls and lsof) to tell you the partition layout; if anyone has a better idea I'd love to hear it).

**Comment by tuxuser** [comment]
This issue is solved, isn't it?

**Comment by steadfasterX** [comment]
i can speak for the G4 only but here: yes. tested on LP, MM and even the unofficial Nougat

**Comment by Lekensteyn** [comment]
Yep, this issue should be obsoleted by #27
